### PR TITLE
Remove dependency on `itertools`

### PR DESCRIPTION
**Pull request by fornwall**

### CODE REVIEW

**Comment by jswrenn** [comment]
Happy to merge this! Looks like I'll need to adjust CI a bit, however...

**Comment by fornwall** [comment]
@jswrenn Thanks, CI seems fixed now!

**Comment by jswrenn** [comment]
Merged! Sorry for the delay; I needed to work out some kinks with CI. 

Is there any particular reason you wanted to remove itertools that I should be aware of?

**Comment by fornwall** [comment]
Thanks!

> Is there any particular reason you wanted to remove itertools that I should be aware of?

No special reason except to prevent dependency bloat. Got a warning from [cargo deny](https://github.com/EmbarkStudios/cargo-deny) about having duplicated itertools versions in the dependency tree, so initially came here just to bump itertools. But seeing that it was probably better to remove for now I went for that instead.

**Pull request merged**
